variables:
  - name: subscriptionId
    value: ## @TODO: Add subscription ID
  - name: resourceGroup
    value: ## @TODO: Add resource group
  - name: adfName
    value: ## @TODO: Add ADF name
  - name: deployEnvironment
    value: ## @TODO: Add deployment environment
  - name: serviceConnection
    value: ## @TODO: Add service connection
  - name: location
    value: ## @TODO: Add location
  - name: overrideParameters
    value: ""